FROM perl:latest
MAINTAINER mitch.hulscher@nepworldwide.nl

RUN apt-get update \
 && apt-get install -y \
  jq \
  curl \
 && curl -o /tmp/zabbix-release.deb http://repo.zabbix.com/zabbix/3.0/debian/pool/main/z/zabbix-release/zabbix-release_3.0-1+jessie_all.deb \
 && dpkg -i /tmp/zabbix-release.deb \
 && apt-get update \
 && apt-get install -y zabbix-sender \
 && rm -f /tmp/zabbix-release.deb \
 && rm -rf /var/lib/apt/lists/* \
 && cpanm Carton

ADD bin               /app/bin
ADD cpanfile          /app
ADD cpanfile.snapshot /app

WORKDIR "/app"

ENTRYPOINT ["/app/bin/build.sh"]
